<?php

namespace ContainerI1IzD83;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IJjNPrZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iJjNPrZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iJjNPrZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\Admin\\PersonCrudController::autocomplete' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::batchDelete' => ['privates', '.service_locator.twrFs.m', 'get_ServiceLocator_TwrFs_MService', true],
            'App\\Controller\\Admin\\PersonCrudController::configureActions' => ['privates', '.service_locator.UrOEf8r', 'get_ServiceLocator_UrOEf8rService', true],
            'App\\Controller\\Admin\\PersonCrudController::configureAssets' => ['privates', '.service_locator.wvbCcwL', 'get_ServiceLocator_WvbCcwLService', true],
            'App\\Controller\\Admin\\PersonCrudController::configureCrud' => ['privates', '.service_locator.Nb584vp', 'get_ServiceLocator_Nb584vpService', true],
            'App\\Controller\\Admin\\PersonCrudController::configureFilters' => ['privates', '.service_locator.kud45L1', 'get_ServiceLocator_Kud45L1Service', true],
            'App\\Controller\\Admin\\PersonCrudController::configureResponseParameters' => ['privates', '.service_locator.vMUOjiq', 'get_ServiceLocator_VMUOjiqService', true],
            'App\\Controller\\Admin\\PersonCrudController::createEditForm' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController::createEditFormBuilder' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController::createIndexQueryBuilder' => ['privates', '.service_locator.lng3o3t', 'get_ServiceLocator_Lng3o3tService', true],
            'App\\Controller\\Admin\\PersonCrudController::createNewForm' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController::createNewFormBuilder' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController::delete' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::deleteEntity' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\PersonCrudController::detail' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::edit' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::index' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::new' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::persistEntity' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\PersonCrudController::renderFilters' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController::updateEntity' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator.t7nLwyX', 'get_ServiceLocator_T7nLwyXService', true],
            'App\\Controller\\Admin\\PersonCrudController:autocomplete' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:batchDelete' => ['privates', '.service_locator.twrFs.m', 'get_ServiceLocator_TwrFs_MService', true],
            'App\\Controller\\Admin\\PersonCrudController:configureActions' => ['privates', '.service_locator.UrOEf8r', 'get_ServiceLocator_UrOEf8rService', true],
            'App\\Controller\\Admin\\PersonCrudController:configureAssets' => ['privates', '.service_locator.wvbCcwL', 'get_ServiceLocator_WvbCcwLService', true],
            'App\\Controller\\Admin\\PersonCrudController:configureCrud' => ['privates', '.service_locator.Nb584vp', 'get_ServiceLocator_Nb584vpService', true],
            'App\\Controller\\Admin\\PersonCrudController:configureFilters' => ['privates', '.service_locator.kud45L1', 'get_ServiceLocator_Kud45L1Service', true],
            'App\\Controller\\Admin\\PersonCrudController:configureResponseParameters' => ['privates', '.service_locator.vMUOjiq', 'get_ServiceLocator_VMUOjiqService', true],
            'App\\Controller\\Admin\\PersonCrudController:createEditForm' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController:createEditFormBuilder' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController:createIndexQueryBuilder' => ['privates', '.service_locator.lng3o3t', 'get_ServiceLocator_Lng3o3tService', true],
            'App\\Controller\\Admin\\PersonCrudController:createNewForm' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController:createNewFormBuilder' => ['privates', '.service_locator.Lazlz4J', 'get_ServiceLocator_Lazlz4JService', true],
            'App\\Controller\\Admin\\PersonCrudController:delete' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:deleteEntity' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\PersonCrudController:detail' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:edit' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:index' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:new' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:persistEntity' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\Admin\\PersonCrudController:renderFilters' => ['privates', '.service_locator.t9B7cZ4', 'get_ServiceLocator_T9B7cZ4Service', true],
            'App\\Controller\\Admin\\PersonCrudController:updateEntity' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\Admin\\PersonCrudController::autocomplete' => '?',
            'App\\Controller\\Admin\\PersonCrudController::batchDelete' => '?',
            'App\\Controller\\Admin\\PersonCrudController::configureActions' => '?',
            'App\\Controller\\Admin\\PersonCrudController::configureAssets' => '?',
            'App\\Controller\\Admin\\PersonCrudController::configureCrud' => '?',
            'App\\Controller\\Admin\\PersonCrudController::configureFilters' => '?',
            'App\\Controller\\Admin\\PersonCrudController::configureResponseParameters' => '?',
            'App\\Controller\\Admin\\PersonCrudController::createEditForm' => '?',
            'App\\Controller\\Admin\\PersonCrudController::createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\PersonCrudController::createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\PersonCrudController::createNewForm' => '?',
            'App\\Controller\\Admin\\PersonCrudController::createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\PersonCrudController::delete' => '?',
            'App\\Controller\\Admin\\PersonCrudController::deleteEntity' => '?',
            'App\\Controller\\Admin\\PersonCrudController::detail' => '?',
            'App\\Controller\\Admin\\PersonCrudController::edit' => '?',
            'App\\Controller\\Admin\\PersonCrudController::index' => '?',
            'App\\Controller\\Admin\\PersonCrudController::new' => '?',
            'App\\Controller\\Admin\\PersonCrudController::persistEntity' => '?',
            'App\\Controller\\Admin\\PersonCrudController::renderFilters' => '?',
            'App\\Controller\\Admin\\PersonCrudController::updateEntity' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\Admin\\PersonCrudController:autocomplete' => '?',
            'App\\Controller\\Admin\\PersonCrudController:batchDelete' => '?',
            'App\\Controller\\Admin\\PersonCrudController:configureActions' => '?',
            'App\\Controller\\Admin\\PersonCrudController:configureAssets' => '?',
            'App\\Controller\\Admin\\PersonCrudController:configureCrud' => '?',
            'App\\Controller\\Admin\\PersonCrudController:configureFilters' => '?',
            'App\\Controller\\Admin\\PersonCrudController:configureResponseParameters' => '?',
            'App\\Controller\\Admin\\PersonCrudController:createEditForm' => '?',
            'App\\Controller\\Admin\\PersonCrudController:createEditFormBuilder' => '?',
            'App\\Controller\\Admin\\PersonCrudController:createIndexQueryBuilder' => '?',
            'App\\Controller\\Admin\\PersonCrudController:createNewForm' => '?',
            'App\\Controller\\Admin\\PersonCrudController:createNewFormBuilder' => '?',
            'App\\Controller\\Admin\\PersonCrudController:delete' => '?',
            'App\\Controller\\Admin\\PersonCrudController:deleteEntity' => '?',
            'App\\Controller\\Admin\\PersonCrudController:detail' => '?',
            'App\\Controller\\Admin\\PersonCrudController:edit' => '?',
            'App\\Controller\\Admin\\PersonCrudController:index' => '?',
            'App\\Controller\\Admin\\PersonCrudController:new' => '?',
            'App\\Controller\\Admin\\PersonCrudController:persistEntity' => '?',
            'App\\Controller\\Admin\\PersonCrudController:renderFilters' => '?',
            'App\\Controller\\Admin\\PersonCrudController:updateEntity' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
