# config/packages/easy_admin.yaml
easy_admin:
    entities:
        - class: App\Entity\Person
          label: 'Membres'
          list:
            - { property: 'photo_pro', label: 'Photo', type: 'image' }
            - { property: 'photo_fun', label: 'Photo', type: 'image' }
          edit:
            - { property: 'photo_pro', label: 'Photo', type: 'vich_image' }
            - { property: 'photo_fun', label: 'Photo', type: 'vich_image' }
          # Configure other options for this entity
        - class: App\Entity\Administrators
          label: "Administrateurs"
    allow_all_actions: true
    design:
      login:
        # Nom de la route pour votre page de connexion
        route: 'login'