version: "3.0"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
      - "5173:5173"
    volumes:
      - front
    restart: always

volumes:
  front:
