<?php

namespace ContainerB7zH4Xs;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPentatrionVite_CacheWarmerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pentatrion_vite.cache_warmer' shared service.
     *
     * @return \Pentatrion\ViteBundle\CacheWarmer\EntrypointsCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/CacheWarmer/AbstractPhpFileCacheWarmer.php';
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/CacheWarmer/EntrypointsCacheWarmer.php';

        return $container->privates['pentatrion_vite.cache_warmer'] = new \Pentatrion\ViteBundle\CacheWarmer\EntrypointsCacheWarmer((\dirname(__DIR__, 4).'/public'), $container->parameters['pentatrion_vite.configs'], ($container->targetDir.''.'/pentatrion_vite.cache.php'));
    }
}
