<?php

namespace ContainerL8zRdeG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPentatrionVite_TagRendererDefaultService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'pentatrion_vite.tag_renderer[_default]' shared service.
     *
     * @return \Pentatrion\ViteBundle\Service\TagRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/pentatrion/vite-bundle/src/Service/TagRenderer.php';

        return $container->privates['pentatrion_vite.tag_renderer[_default]'] = new \Pentatrion\ViteBundle\Service\TagRenderer([], [], [], []);
    }
}
