<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI1IzD83\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI1IzD83/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI1IzD83.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI1IzD83\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI1IzD83\App_KernelDevDebugContainer([
    'container.build_hash' => 'I1IzD83',
    'container.build_id' => '3e2fd0a5',
    'container.build_time' => 1705574556,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI1IzD83');
