<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'pentatrion_vite_build_proxy' => [['path'], ['_controller' => 'Pentatrion\\ViteBundle\\Controller\\ViteController::proxyBuild'], ['path' => '.+'], [['variable', '/', '.+', 'path', true], ['text', '/build']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'persons_index' => [[], ['_controller' => 'App\\Controller\\PersonController::index'], [], [['text', '/persons']], [], [], []],
    'person_create' => [[], ['_controller' => 'App\\Controller\\PersonController::create'], [], [['text', '/persons/create']], [], [], []],
    'App\Controller\Admin\DashboardController::index' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'App\Controller\DefaultController::index' => [[], ['_controller' => 'App\\Controller\\DefaultController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\SecurityController::login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
];
