<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXea2fQ1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXea2fQ1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXea2fQ1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXea2fQ1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXea2fQ1\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xea2fQ1',
    'container.build_id' => '872d2cec',
    'container.build_time' => 1705579526,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXea2fQ1');
