<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8clqMM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8clqMM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD8clqMM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD8clqMM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD8clqMM\App_KernelDevDebugContainer([
    'container.build_hash' => 'D8clqMM',
    'container.build_id' => '0ec8cb8a',
    'container.build_time' => 1705597725,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8clqMM');
