<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB7zH4Xs\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB7zH4Xs/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB7zH4Xs.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB7zH4Xs\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB7zH4Xs\App_KernelDevDebugContainer([
    'container.build_hash' => 'B7zH4Xs',
    'container.build_id' => '8e8cef11',
    'container.build_time' => 1705584806,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB7zH4Xs');
