<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default.entrypoints' => 0,

], [

0 => [
    'base' => '/build/',
    'entryPoints' => [
        'app' => [
            'js' => [
                'http://127.0.0.1:5173/build/assets/main.jsx',
            ],
        ],
    ],
    'legacy' => false,
    'metadatas' => [],
    'version' => [
        '6.3.2',
        6,
        3,
        2,
    ],
    'viteServer' => 'http://127.0.0.1:5173',
],

]];
